# Generated by Django 5.2.1 on 2025-05-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='descricao',
            field=models.CharField(verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='uf',
            field=models.CharField(max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='instituicaoensino',
            name='site',
            field=models.CharField(verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='instituicaoensino',
            name='telefone',
            field=models.CharField(verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de inicio'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='data_previsao_termino',
            field=models.DateField(verbose_name='Previsao de termino'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='descricao',
            field=models.CharField(verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_nasc',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.CharField(verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='mae',
            field=models.CharField(verbose_name='Mãe'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pai',
            field=models.CharField(verbose_name='Pai'),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='nome',
            field=models.CharField(verbose_name='Nome do Turno'),
        ),
    ]
