# Generated by Django 5.2.1 on 2025-05-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_curso_duracao_meses'),
    ]

    operations = [
    ]
