# Generated by Django 5.2.1 on 2025-05-26 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_turnos_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cidade',
            options={},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={},
        ),
        migrations.RenameField(
            model_name='frequencia',
            old_name='Pessoa',
            new_name='pessoa',
        ),
        migrations.AddField(
            model_name='curso',
            name='instituicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.instituicaoensino', verbose_name='Instituição'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.turma', verbose_name='Turma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cidade',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uf', verbose_name='UF'),
        ),
    ]
