# Generated by Django 5.2.1 on 2025-05-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_uf_alter_cidade_options_alter_curso_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidade',
            options={'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='uf',
            options={'verbose_name': 'UF', 'verbose_name_plural': 'USs'},
        ),
    ]
