# Generated by Django 5.2.1 on 2025-05-19 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20250519_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaotipo',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Tipo da avaliação'),
        ),
        migrations.AlterField(
            model_name='cursodisciplina',
            name='carga_horaria',
            field=models.IntegerField(verbose_name='Carga Horária'),
        ),
        migrations.AlterField(
            model_name='cursodisciplina',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='cursodisciplina',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turnos', verbose_name='Turno'),
        ),
    ]
