# Generated by Django 5.2.1 on 2025-05-19 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_avaliacaotipo_nome_and_more'),
    ]

    operations = [
    ]
