# Generated by Django 5.2.1 on 2025-05-19 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20250519_0948'),
    ]

    operations = [
    ]
