# Generated by Django 5.2.1 on 2025-05-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20250519_0955'),
    ]

    operations = [
    ]
